services:
  heatmap:
    build:
      target: development
    image: heatmap-development
    container_name: heatmap-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - heatmap
    environment:
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
    depends_on:
      redis:
        condition: service_started

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1
    networks:
      - heatmap

networks:
  heatmap:
    driver: bridge
    name: heatmap

volumes:
  redis_data:
